"""Tests that every implemented lockfile handler is reachable through scan_with_metrics().

The defect (pre-fix): handlers exist for package-lock.json, Gemfile.lock, go.sum,
and Cargo.lock in dep_collector.py, and the dispatch in main.py calls them, but
_inventory() does not place those filenames in the supported-file set. Therefore
they never execute through the main scan path.
"""
import tempfile
import unittest
from pathlib import Path

from scanner.main import scan_with_metrics

# Contents with at least one known crypto dependency per lockfile.
REQUIREMENTS_TXT = "cryptography>=41.0\n"
POM_XML = """<project xmlns="http://maven.apache.org/POM/4.0.0">
  <dependencies>
    <dependency><groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk18on</artifactId></dependency>
  </dependencies>
</project>"""
PACKAGE_LOCK = """{
  "lockfileVersion": "3",
  "packages": {
    "": {"name": "app", "version": "1.0.0"},
    "node_modules/crypto-js": {"version": "4.2.0"}
  }
}"""
GEMFILE_LOCK = """GEM
  remote: https://rubygems.org/
  specs:
    openssl (2.2.0)

GEM
  remote: https://rubygems.org/
  specs:
"""
GO_SUM = """\
std stdlib go1.22
golang.org/x/crypto v0.14.0 h1:wcQYHkvc2kmZftDVAa6nZb0+fVpg2Wn4ehH/Um9cFxI=
golang.org/x/crypto v0.14.0/go.mod h1:MVFd36IqK+ZRMNq4DnspNMyqU0kR+2ZAE4Q3sLb4N1M=
"""
CARGO_LOCK = """\
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "ring"
version = "0.17.8"
"""


class DependencyLockfileReachabilityTests(unittest.TestCase):
    """Each test creates a repo with one lockfile and verifies the main scan
    path processes it through the dep collector."""

    # ------------------------------------------------------------------
    # requirements.txt
    # ------------------------------------------------------------------
    def test_requirements_txt_is_reachable_and_produces_evidence(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "requirements.txt").write_text(REQUIREMENTS_TXT)
            evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["in_scope_files"], 1)
        self.assertEqual(metrics["scanned_files"], 1)
        self.assertEqual(metrics["failed_files"], 0)
        self.assertEqual(metrics["coverage_pct"], 100.0)
        self.assertGreater(metrics["collector_stats"]["dep"], 0)
        flat = [item for items in evidence.values() for item in items]
        dep_items = [item for item in flat if item.get("source") == "dep"]
        self.assertTrue(dep_items, "dependency collector should produce evidence")
        algorithms = {item["algorithm"] for item in dep_items}
        self.assertTrue(algorithms & {"RSA", "AES", "ECDSA", "Ed25519", "SHA-256"})

    def test_requirements_txt_is_counted_in_total_and_supported(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "requirements.txt").write_text(REQUIREMENTS_TXT)
            (Path(directory) / "README.md").write_text("# project\n")
            _evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["total_files"], 2)
        self.assertEqual(metrics["in_scope_files"], 1)

    # ------------------------------------------------------------------
    # pom.xml
    # ------------------------------------------------------------------
    def test_pom_xml_is_reachable_and_produces_evidence(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "pom.xml").write_text(POM_XML)
            evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["in_scope_files"], 1)
        self.assertEqual(metrics["scanned_files"], 1)
        self.assertEqual(metrics["coverage_pct"], 100.0)
        self.assertGreater(metrics["collector_stats"]["dep"], 0)
        flat = [item for items in evidence.values() for item in items]
        dep_items = [item for item in flat if item.get("source") == "dep"]
        self.assertTrue(any(item["algorithm"] == "RSA" for item in dep_items))

    # ------------------------------------------------------------------
    # package-lock.json
    # ------------------------------------------------------------------
    def test_package_lock_is_reachable_and_produces_evidence(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "package-lock.json").write_text(PACKAGE_LOCK)
            evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["in_scope_files"], 1)
        self.assertEqual(metrics["scanned_files"], 1)
        self.assertEqual(metrics["coverage_pct"], 100.0)
        self.assertGreater(metrics["collector_stats"]["dep"], 0)
        flat = [item for items in evidence.values() for item in items]
        dep_items = [item for item in flat if item.get("source") == "dep"]
        self.assertTrue(dep_items, "dep collector should produce evidence from package-lock.json")
        algorithms = {item["algorithm"] for item in dep_items}
        self.assertTrue(algorithms & {"AES", "DES", "SHA-256", "SHA-1", "HMAC", "RSA", "ECDSA", "Ed25519", "TLS"})

    def test_package_lock_is_counted_in_total_and_supported(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "package-lock.json").write_text(PACKAGE_LOCK)
            (Path(directory) / "app.js").write_text("console.log('hi');\n")
            _evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["total_files"], 2)
        self.assertEqual(metrics["in_scope_files"], 2)

    # ------------------------------------------------------------------
    # Gemfile.lock
    # ------------------------------------------------------------------
    def test_gemfile_lock_is_reachable_and_produces_evidence(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "Gemfile.lock").write_text(GEMFILE_LOCK)
            evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["in_scope_files"], 1)
        self.assertEqual(metrics["scanned_files"], 1)
        self.assertEqual(metrics["coverage_pct"], 100.0)
        self.assertGreater(metrics["collector_stats"]["dep"], 0)
        flat = [item for items in evidence.values() for item in items]
        dep_items = [item for item in flat if item.get("source") == "dep"]
        self.assertTrue(dep_items, "dep collector should produce evidence from Gemfile.lock")
        algorithms = {item["algorithm"] for item in dep_items}
        self.assertTrue(algorithms & {"RSA", "ECDSA", "AES", "Ed25519", "ChaCha20"})

    def test_gemfile_lock_is_counted_in_total_and_supported(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "Gemfile.lock").write_text(GEMFILE_LOCK)
            (Path(directory) / "README").write_text("# gem app\n")
            _evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["total_files"], 2)
        self.assertEqual(metrics["in_scope_files"], 1)

    # ------------------------------------------------------------------
    # go.sum
    # ------------------------------------------------------------------
    def test_go_sum_is_reachable_and_produces_evidence(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "go.sum").write_text(GO_SUM)
            evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["in_scope_files"], 1)
        self.assertEqual(metrics["scanned_files"], 1)
        self.assertEqual(metrics["coverage_pct"], 100.0)
        self.assertGreater(metrics["collector_stats"]["dep"], 0)
        flat = [item for items in evidence.values() for item in items]
        dep_items = [item for item in flat if item.get("source") == "dep"]
        self.assertTrue(dep_items, "dep collector should produce evidence from go.sum")
        algorithms = {item["algorithm"] for item in dep_items}
        self.assertTrue(algorithms & {"SHA-256", "ECDSA", "Ed25519", "ChaCha20", "RSA", "HMAC"})

    def test_go_sum_is_counted_in_total_and_supported(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "go.sum").write_text(GO_SUM)
            (Path(directory) / "main.go").write_text("package main\n")
            _evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["total_files"], 2)
        self.assertEqual(metrics["in_scope_files"], 2)

    # ------------------------------------------------------------------
    # Cargo.lock
    # ------------------------------------------------------------------
    def test_cargo_lock_is_reachable_and_produces_evidence(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "Cargo.lock").write_text(CARGO_LOCK)
            evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["in_scope_files"], 1)
        self.assertEqual(metrics["scanned_files"], 1)
        self.assertEqual(metrics["coverage_pct"], 100.0)
        self.assertGreater(metrics["collector_stats"]["dep"], 0)
        flat = [item for items in evidence.values() for item in items]
        dep_items = [item for item in flat if item.get("source") == "dep"]
        self.assertTrue(dep_items, "dep collector should produce evidence from Cargo.lock")
        algorithms = {item["algorithm"] for item in dep_items}
        self.assertTrue(algorithms & {"AES", "SHA-256", "ECDSA", "TLS", "Ed25519"})

    def test_cargo_lock_is_counted_in_total_and_supported(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "Cargo.lock").write_text(CARGO_LOCK)
            (Path(directory) / "Cargo.toml").write_text("[package]\nname = \"app\"\n")
            _evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["total_files"], 2)
        self.assertEqual(metrics["in_scope_files"], 1)

    # ------------------------------------------------------------------
    # Malformed and negative cases
    # ------------------------------------------------------------------
    def test_malformed_package_lock_counts_as_failure_not_finding(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "package-lock.json").write_text("not valid json {{{")
            evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["in_scope_files"], 1)
        self.assertEqual(metrics["failed_files"], 1)
        self.assertEqual(metrics["scanned_files"], 0)
        self.assertEqual(metrics["coverage_pct"], 0.0)
        self.assertFalse(any(item.get("source") == "dep" for items in evidence.values() for item in items))

    def test_empty_gemfile_lock_produces_no_findings_but_counts_as_scanned(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "Gemfile.lock").write_text(
                "GEM\n  remote: https://rubygems.org/\n\nGEM\n  remote: https://rubygems.org/\n  specs:\n"
            )
            evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["in_scope_files"], 1)
        self.assertEqual(metrics["scanned_files"], 1)
        self.assertEqual(metrics["failed_files"], 0)
        flat = [item for items in evidence.values() for item in items]
        dep_items = [item for item in flat if item.get("source") == "dep"]
        self.assertEqual(dep_items, [])

    def test_go_sum_without_crypto_modules_produces_no_findings(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "go.sum").write_text(
                "std stdlib go1.22\n"
                "example.com/some-lib v1.0.0 h1:abc=\n"
                "example.com/some-lib v1.0.0/go.mod h1:def=\n"
            )
            evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["in_scope_files"], 1)
        self.assertEqual(metrics["scanned_files"], 1)
        flat = [item for items in evidence.values() for item in items]
        dep_items = [item for item in flat if item.get("source") == "dep"]
        self.assertEqual(dep_items, [])

    def test_cargo_lock_without_crypto_crates_produces_no_findings(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "Cargo.lock").write_text(
                '[[package]]\nname = "serde"\nversion = "1.0"\n'
            )
            evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["in_scope_files"], 1)
        self.assertEqual(metrics["scanned_files"], 1)
        flat = [item for items in evidence.values() for item in items]
        dep_items = [item for item in flat if item.get("source") == "dep"]
        self.assertEqual(dep_items, [])

    def test_malformed_cargo_lock_counts_as_failure(self):
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "Cargo.lock").write_text("<<<not toml>>>")
            _evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["in_scope_files"], 1)
        self.assertEqual(metrics["failed_files"], 1)
        self.assertEqual(metrics["coverage_pct"], 0.0)

    def test_all_six_lockfile_types_in_same_repo_all_reachable(self):
        """When multiple lockfile types exist in one repo, all must be in scope
        and processed."""
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "requirements.txt").write_text(REQUIREMENTS_TXT)
            (Path(directory) / "pom.xml").write_text(POM_XML)
            (Path(directory) / "package-lock.json").write_text(PACKAGE_LOCK)
            (Path(directory) / "Gemfile.lock").write_text(GEMFILE_LOCK)
            (Path(directory) / "go.sum").write_text(GO_SUM)
            (Path(directory) / "Cargo.lock").write_text(CARGO_LOCK)
            _evidence, metrics = scan_with_metrics(directory)

        self.assertEqual(metrics["total_files"], 6)
        self.assertEqual(metrics["in_scope_files"], 6)
        self.assertEqual(metrics["scanned_files"], 6)
        self.assertEqual(metrics["failed_files"], 0)
        self.assertEqual(metrics["coverage_pct"], 100.0)
        self.assertGreater(metrics["collector_stats"]["dep"], 0)

    def test_dep_collector_stat_attributes_lockfile_evidence(self):
        """Evidence produced from lockfiles must be attributed to the 'dep'
        collector, not to rule or ast."""
        with tempfile.TemporaryDirectory() as directory:
            (Path(directory) / "Gemfile.lock").write_text(GEMFILE_LOCK)
            _evidence, metrics = scan_with_metrics(directory)

        total_dep = metrics["collector_stats"]["dep"]
        self.assertGreater(total_dep, 0)
        self.assertEqual(metrics["collector_stats"]["ast"], 0)
        self.assertEqual(metrics["collector_stats"]["rule"], 0)


if __name__ == "__main__":
    unittest.main(verbosity=2)
